# Generated by Django 5.0.2 on 2024-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
