# Generated by Django 5.0.2 on 2024-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
